<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue'
import {requestJSON} from '../api'
const prompt=ref(''),provider=ref('custom'),ratio=ref('2:1'),resolution=ref(''),refs=ref([null,null,null,null]),items=ref([]),error=ref(''),busy=ref(false),preview=ref('')
const running=computed(()=>items.value.some(x=>x.status==='running'))
const url=(id,name='result.png')=>`/api/image-studio/${id}/files/${name}`
let timer
async function refresh(){try{items.value=(await requestJSON('/api/image-studio')).items}catch(e){error.value=e.message}}
function add(item){const i=refs.value.findIndex(x=>!x);if(i<0){error.value='最多4张参考图，请先移除一张';return}refs.value[i]=item;error.value=`已添加为图${i+1}`}
async function upload(e){busy.value=true;try{for(const file of e.target.files){if(refs.value.every(Boolean))throw Error('最多4张参考图');const body=new FormData();body.append('file',file);const {asset}=await requestJSON('/api/editor/uploads',{method:'POST',body});add({id:asset.id,url:asset.url||`/api/editor/uploads/${asset.id}`})}}catch(e){error.value=e.message}finally{busy.value=false;e.target.value=''}}
async function generate(){const last=refs.value.findLastIndex(Boolean);if(refs.value.slice(0,last+1).some(x=>!x)){error.value='请补齐参考图空位，确保图号与实际提交一致';return}busy.value=true;error.value='';try{await requestJSON('/api/image-studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt.value,provider:provider.value,ratio:ratio.value,resolution:resolution.value,references:refs.value.filter(Boolean).map(x=>x.id)})});await refresh()}catch(e){error.value=e.message}finally{busy.value=false}}
async function remove(id=''){if(!confirm('删除'+(id?'这条':'全部')+'历史及本地图片？已下载的副本不受影响。'))return;try{await requestJSON('/api/image-studio'+(id?'?identity='+id:''),{method:'DELETE'});refs.value=refs.value.map(x=>x?.id.startsWith('history:')&&(!id||x.id.split(':')[1]===id)?null:x);await refresh()}catch(e){error.value=e.message}}
function reuse(item){prompt.value=item.prompt;provider.value=item.provider;ratio.value=item.ratio;resolution.value=item.resolution;refs.value=[null,null,null,null];item.references.forEach((name,i)=>refs.value[i]={id:`history:${item.id}:${name}`,url:url(item.id,name)});window.scrollTo({top:0,behavior:'smooth'})}
onMounted(()=>{refresh();timer=setInterval(refresh,3000)});onUnmounted(()=>clearInterval(timer))
</script>
<template>
<section class="content image-workspace">
 <div class="page-heading"><div><p class="eyebrow">IMAGE STUDIO</p><h1>图片工作室</h1><p class="muted">每次一张，自由描述。共用“接口与服务”的图像配置。</p></div></div>
 <div class="compose"><label>提示词<textarea v-model="prompt" rows="6" maxlength="20000" placeholder="描述你想生成的图片，可直接提及图1、图2……" /></label>
 <div class="options"><label>图像服务<select v-model="provider"><option value="custom">自己的 API</option><option value="pool">OCV 号池</option></select></label><label>图片比例<select v-model="ratio"><option>2:1</option><option>16:9</option><option>1:1</option><option>9:16</option></select></label><label>分辨率<select v-model="resolution"><option value="">跟随全局</option><option value="1k">1K</option><option value="2k">2K</option><option value="4k">4K</option></select></label></div>
 <div class="refs"><div v-for="(r,i) in refs" :key="i" class="ref"><span>图{{i+1}}</span><template v-if="r"><button @click="preview=r.url"><img :src="r.url" :alt="'图'+(i+1)" /></button><button @click="refs[i]=null">移除</button></template><small v-else>空位</small></div><label>上传参考图<input type="file" accept="image/png,image/jpeg,image/webp" multiple :disabled="busy" @change="upload" /></label></div>
 <p class="muted">参考图可选，最多4张，点击放大。移除后保留编号，新图片优先填补空位。</p><div class="actions"><span class="muted">提示词原样提交；失败报错，不自动重试。</span><button class="primary" :disabled="busy||running||!prompt.trim()" @click="generate">{{running?'正在生成…':busy?'正在处理…':'生成图片'}}</button></div></div>
 <p v-if="error" role="alert" class="studio-notice">{{error}}<button @click="error=''">×</button></p>
 <div class="section-heading"><h2>生成历史 <small>{{items.length}}</small></h2><button :disabled="running||!items.length" @click="remove()">清空历史</button></div>
 <div class="history"><article v-for="item in items" :key="item.id"><button v-if="item.status==='completed'" class="result" @click="preview=url(item.id)"><img :src="url(item.id)" alt="生成结果" /></button><p>{{item.message}}</p><small class="muted">{{new Date(item.created_at*1000).toLocaleString()}} · {{item.ratio}} · {{item.resolution.toUpperCase()}}<template v-if="item.width"> · {{item.width}} × {{item.height}}</template></small><details><summary>提示词与参考图</summary><p class="prompt">{{item.prompt}}</p><div class="refs"><button v-for="(name,i) in item.references" :key="name" @click="preview=url(item.id,name)">图{{i+1}}<img :src="url(item.id,name)" width="64" /></button></div></details><div class="actions"><template v-if="item.status==='completed'"><a :href="url(item.id)" :download="'OCV-'+item.id+'.png'">下载图片</a><button @click="add({id:'history:'+item.id,url:url(item.id)})">用作参考图</button></template><button @click="reuse(item)">复用参数</button><button :disabled="running" @click="remove(item.id)">删除</button></div></article></div>
 <div v-if="preview" class="preview" @click.self="preview=''"><button @click="preview=''">关闭 ×</button><img :src="preview" alt="图片预览" /></div>
</section>
</template>
<style scoped>
.compose,article{border:1px solid var(--ocv-border,#35433e);border-radius:16px;padding:24px;background:var(--ocv-panel,#202825)}label{display:grid;gap:8px}textarea{width:100%;resize:vertical;margin-top:8px}.options,.refs,.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center}.options{margin:20px 0}.options select{min-width:150px}.ref{display:grid;gap:5px;justify-items:center;min-width:90px;padding:8px;border:1px solid #425048;border-radius:9px}.ref img{width:76px;height:64px;object-fit:contain}.ref button{padding:4px}input[type=file]{max-width:240px}.actions{margin-top:16px}.actions>.primary{margin-left:auto}.history{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:20px}.result{width:100%;padding:0!important;overflow:hidden}.result img{width:100%;height:240px;object-fit:contain}.prompt{white-space:pre-wrap;overflow-wrap:anywhere}.preview{position:fixed;inset:0;z-index:10000;background:#000d;display:flex;align-items:center;justify-content:center}.preview>img{max-width:92vw;max-height:88vh;object-fit:contain}.preview>button{position:absolute;right:25px;top:20px}.section-heading{margin-top:30px}
</style>
